"""empty message

Revision ID: d3f8ec43541b
Revises: 
Create Date: 2022-01-19 21:50:18.037133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f8ec43541b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('brand', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('manufacture_year', sa.Integer(), nullable=True),
    sa.Column('isAvailable', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('kilometers_traveled', sa.Integer(), nullable=True),
    sa.Column('accepted_fuel', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('optional_features', sa.String(), nullable=True),
    sa.Column('gearshift_type', sa.String(), nullable=True),
    sa.Column('engine_capacity', sa.String(), nullable=True),
    sa.Column('photos', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discountCoupon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isValid', sa.Boolean(), nullable=True),
    sa.Column('promotion_name', sa.String(length=50), nullable=True),
    sa.Column('discount_value', sa.String(length=10), nullable=True),
    sa.Column('valid_through', sa.String(length=15), nullable=True),
    sa.Column('accepted_payment_method', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motorcycle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('brand', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('manufacture_year', sa.Integer(), nullable=True),
    sa.Column('isAvailable', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('kilometers_traveled', sa.Integer(), nullable=True),
    sa.Column('accepted_fuel', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('optional_features', sa.String(), nullable=True),
    sa.Column('gearshift_type', sa.String(), nullable=True),
    sa.Column('engine_capacity', sa.String(), nullable=True),
    sa.Column('photos', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('favorites', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('shoppingCart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('products', sa.PickleType(), nullable=True),
    sa.Column('qnt_products', sa.Integer(), nullable=True),
    sa.Column('price_before_coupon', sa.Float(), nullable=True),
    sa.Column('price_final', sa.Float(), nullable=True),
    sa.Column('used_coupon', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shoppingCart')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('motorcycle')
    op.drop_table('discountCoupon')
    op.drop_table('car')
    # ### end Alembic commands ###
